import type { TripLogRow } from "../types/device-workspace-trip-route";

export type ExportColumn = { label: string; value: (row: TripLogRow) => string };
export type ExportFormat = "xlsx" | "csv" | "pdf";

const COMPANY = "ALELS TECH INDONESIA";
const DOCUMENT_TITLE = "Device Log History";
const LOGO_URL = "/assets/logo-card.png";
const LOGO_FALLBACK_URL = "/assets/alels-mark-light.png";

export async function exportTripLog(format: ExportFormat, rows: TripLogRow[], columns: ExportColumn[], imei: string, selectionCount: number) {
  const generated = new Date().toLocaleString("id-ID");
  if (format === "csv") return exportCsv(rows, columns, imei, selectionCount, generated);

  const logo = await loadAlelsLogo();
  if (format === "xlsx") return exportXlsx(rows, columns, imei, selectionCount, generated, logo.png);
  return exportPdf(rows, columns, imei, selectionCount, generated, logo.jpeg);
}

function exportCsv(rows: TripLogRow[], columns: ExportColumn[], imei: string, selectionCount: number, generated: string) {
  const quote = (value: string) => `"${value.replace(/"/g, '""')}"`;
  const lines = [
    quote(COMPANY),
    quote(DOCUMENT_TITLE),
    `${quote("Device IMEI")},${quote(imei)}`,
    `${quote("Selected Trip/Stop")},${quote(String(selectionCount))}`,
    `${quote("Generated")},${quote(generated)}`,
    quote("Generated by ALELS Platform"),
    "",
    columns.map(column => quote(column.label)).join(","),
    ...rows.map(row => columns.map(column => quote(column.value(row))).join(",")),
  ];
  save(new Blob(["\ufeff", lines.join("\r\n")], { type: "text/csv;charset=utf-8" }), `alels-device-log-${imei}.csv`);
}

function exportXlsx(
  rows: TripLogRow[],
  columns: ExportColumn[],
  imei: string,
  selectionCount: number,
  generated: string,
  logoPng: Uint8Array | null,
) {
  const matrix = [
    [COMPANY],
    [DOCUMENT_TITLE],
    ["Device IMEI", imei],
    ["Selected Trip/Stop", String(selectionCount)],
    ["Generated", generated],
    ["Generated by", "ALELS Platform"],
    [],
    columns.map(column => column.label),
    ...rows.map(row => columns.map(column => column.value(row))),
  ];

  const sharedStrings: string[] = [];
  const sharedIndex = new Map<string, number>();
  const stringIndex = (value: string) => {
    const known = sharedIndex.get(value);
    if (known != null) return known;
    const index = sharedStrings.length;
    sharedStrings.push(value);
    sharedIndex.set(value, index);
    return index;
  };

  const sheetRows = matrix.map((row, rowIndex) => {
    const excelRow = rowIndex + 1;
    const style = excelRow === 1 ? 1 : excelRow === 2 ? 2 : excelRow === 8 ? 3 : 0;
    const cells = row.map((value, columnIndex) => {
      const ref = `${columnName(columnIndex)}${excelRow}`;
      return `<c r="${ref}" t="s" s="${style}"><v>${stringIndex(String(value))}</v></c>`;
    }).join("");
    const height = excelRow === 1 ? ` ht="30" customHeight="1"` : excelRow === 2 ? ` ht="24" customHeight="1"` : "";
    return `<row r="${excelRow}"${height}>${cells}</row>`;
  }).join("");

  const lastColumn = columnName(Math.max(1, columns.length - 1));
  const mergeTo = columnName(Math.min(Math.max(4, columns.length - 1), 8));
  const files: Record<string, string | Uint8Array> = {
    "[Content_Types].xml": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${logoPng ? '<Override PartName="/xl/drawings/drawing1.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/>' : ""}</Types>`,
    "_rels/.rels": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
    "xl/workbook.xml": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Device Log" sheetId="1" r:id="rId1"/></sheets></workbook>`,
    "xl/_rels/workbook.xml.rels": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`,
    "xl/styles.xml": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="4"><font><sz val="10"/><name val="Arial"/></font><font><b/><sz val="18"/><color rgb="FF111827"/><name val="Arial"/></font><font><b/><sz val="13"/><color rgb="FF0369A1"/><name val="Arial"/></font><font><b/><sz val="10"/><color rgb="FFFFFFFF"/><name val="Arial"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF0284C7"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="2"><border/><border><bottom style="medium"><color rgb="FF0284C7"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="1" xfId="0" applyFont="1" applyBorder="1"/><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1"/><xf numFmtId="0" fontId="3" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs></styleSheet>`,
    "xl/worksheets/sheet1.xml": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><cols><col min="1" max="1" width="24" customWidth="1"/><col min="2" max="${Math.max(2, columns.length)}" width="18" customWidth="1"/></cols><sheetData>${sheetRows}</sheetData><mergeCells count="2"><mergeCell ref="A1:${mergeTo}1"/><mergeCell ref="A2:${mergeTo}2"/></mergeCells><autoFilter ref="A8:${lastColumn}${matrix.length}"/><freezePane ySplit="8" topLeftCell="A9" activePane="bottomLeft" state="frozen"/>${logoPng ? '<drawing r:id="rId1"/>' : ""}</worksheet>`,
    "xl/sharedStrings.xml": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="${sharedStrings.length}" uniqueCount="${sharedStrings.length}">${sharedStrings.map(value => `<si><t xml:space="preserve">${xml(value)}</t></si>`).join("")}</sst>`,
  };

  if (logoPng) {
    files["xl/media/logo-card.png"] = logoPng;
    files["xl/worksheets/_rels/sheet1.xml.rels"] = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing" Target="../drawings/drawing1.xml"/></Relationships>`;
    files["xl/drawings/drawing1.xml"] = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><xdr:oneCellAnchor><xdr:from><xdr:col>6</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>0</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from><xdr:ext cx="720000" cy="720000"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="2" name="ALELS Logo"/><xdr:cNvPicPr/></xdr:nvPicPr><xdr:blipFill><a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:embed="rId1"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor></xdr:wsDr>`;
    files["xl/drawings/_rels/drawing1.xml.rels"] = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/logo-card.png"/></Relationships>`;
  }

  save(new Blob([zipStored(files)], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), `alels-device-log-${imei}.xlsx`);
}

function exportPdf(
  rows: TripLogRow[],
  columns: ExportColumn[],
  imei: string,
  selectionCount: number,
  generated: string,
  logoJpeg: Uint8Array | null,
) {
  const tableLines = [
    columns.map(column => column.label).join(" | "),
    ...rows.map(row => columns.map(column => column.value(row)).join(" | ")),
  ];
  const pageSize = 34;
  const pages: string[][] = [];
  for (let offset = 0; offset < tableLines.length; offset += pageSize) pages.push(tableLines.slice(offset, offset + pageSize));
  if (!pages.length) pages.push([]);

  const objects: string[] = [];
  const binaryObjects = new Map<number, Uint8Array>();
  const pageRefs: number[] = [];
  const fontObject = 3;
  objects[fontObject] = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`;
  const boldFontObject = 4;
  objects[boldFontObject] = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>`;

  let imageObject = 0;
  if (logoJpeg) {
    imageObject = 5;
    binaryObjects.set(imageObject, logoJpeg);
  }

  let nextObject = imageObject ? 6 : 5;
  pages.forEach((pageLines, pageIndex) => {
    const header = [
      `BT /F2 15 Tf 76 548 Td (${pdf(COMPANY)}) Tj ET`,
      `BT /F1 10 Tf 76 532 Td (${pdf(DOCUMENT_TITLE)}) Tj ET`,
      `0.008 0.518 0.780 RG 28 518 m 814 518 l S`,
      `BT /F1 8 Tf 28 503 Td (${pdf(`Device IMEI: ${imei}   |   Selected Trip/Stop: ${selectionCount}   |   Generated: ${generated}`)}) Tj ET`,
    ];
    if (imageObject) header.unshift(`q 44 0 0 44 28 525 cm /Im1 Do Q`);

    const body = `BT /F1 6 Tf 28 485 Td ${pageLines.map((line, index) => `${index ? "0 -12 Td " : ""}(${pdf(line.slice(0, 220))}) Tj`).join(" ")} ET`;
    const footer = `BT /F1 7 Tf 28 18 Td (${pdf(`Generated by ALELS Platform | Page ${pageIndex + 1} of ${pages.length}`)}) Tj ET`;
    const content = `${header.join("\n")}\n${body}\n${footer}`;
    const contentObject = nextObject++;
    objects[contentObject] = `<< /Length ${byteLength(content)} >>\nstream\n${content}\nendstream`;
    const pageObject = nextObject++;
    pageRefs.push(pageObject);
    const imageResource = imageObject ? ` /XObject << /Im1 ${imageObject} 0 R >>` : "";
    objects[pageObject] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 ${fontObject} 0 R /F2 ${boldFontObject} 0 R >>${imageResource} >> /Contents ${contentObject} 0 R >>`;
  });

  objects[1] = `<< /Type /Catalog /Pages 2 0 R >>`;
  objects[2] = `<< /Type /Pages /Kids [${pageRefs.map(ref => `${ref} 0 R`).join(" ")}] /Count ${pageRefs.length} >>`;
  if (imageObject && logoJpeg) {
    objects[imageObject] = `<< /Type /XObject /Subtype /Image /Width 600 /Height 400 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${logoJpeg.length} >>`;
  }

  save(new Blob([buildPdf(objects, binaryObjects)], { type: "application/pdf" }), `alels-device-log-${imei}.pdf`);
}

async function loadAlelsLogo(): Promise<{ png: Uint8Array | null; jpeg: Uint8Array | null }> {
  const png = await fetchFirstAsset([LOGO_URL, LOGO_FALLBACK_URL]);
  if (!png) return { png: null, jpeg: null };
  try {
    const blob = new Blob([png], { type: "image/png" });
    const image = await createImageBitmap(blob);
    const canvas = document.createElement("canvas");
    canvas.width = 600;
    canvas.height = 400;
    const context = canvas.getContext("2d");
    if (!context) return { png, jpeg: null };
    context.fillStyle = "#ffffff";
    context.fillRect(0, 0, canvas.width, canvas.height);
    const scale = Math.min(canvas.width / image.width, canvas.height / image.height);
    const width = image.width * scale;
    const height = image.height * scale;
    context.drawImage(image, (canvas.width - width) / 2, (canvas.height - height) / 2, width, height);
    image.close();
    const jpegBlob = await new Promise<Blob | null>(resolve => canvas.toBlob(resolve, "image/jpeg", 0.9));
    return { png, jpeg: jpegBlob ? new Uint8Array(await jpegBlob.arrayBuffer()) : null };
  } catch {
    return { png, jpeg: null };
  }
}

async function fetchFirstAsset(urls: string[]) {
  for (const url of urls) {
    try {
      const response = await fetch(url, { cache: "force-cache" });
      if (response.ok) return new Uint8Array(await response.arrayBuffer());
    } catch { /* use next official asset candidate */ }
  }
  return null;
}

function buildPdf(objects: string[], binaryObjects: Map<number, Uint8Array>) {
  const encoder = new TextEncoder();
  const parts: Uint8Array[] = [encoder.encode("%PDF-1.4\n")];
  const offsets: number[] = [0];
  let length = parts[0].length;
  for (let index = 1; index < objects.length; index++) {
    if (!objects[index]) continue;
    offsets[index] = length;
    const binary = binaryObjects.get(index);
    if (binary) {
      const head = encoder.encode(`${index} 0 obj\n${objects[index]}\nstream\n`);
      const tail = encoder.encode("\nendstream\nendobj\n");
      parts.push(head, binary, tail);
      length += head.length + binary.length + tail.length;
    } else {
      const part = encoder.encode(`${index} 0 obj\n${objects[index]}\nendobj\n`);
      parts.push(part);
      length += part.length;
    }
  }
  const xrefOffset = length;
  let xref = `xref\n0 ${objects.length}\n0000000000 65535 f \n`;
  for (let index = 1; index < objects.length; index++) xref += `${String(offsets[index] || 0).padStart(10, "0")} 00000 n \n`;
  xref += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  parts.push(encoder.encode(xref));
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const output = new Uint8Array(total);
  let cursor = 0;
  parts.forEach(part => { output.set(part, cursor); cursor += part.length; });
  return output;
}

function zipStored(files: Record<string, string | Uint8Array>) {
  const encoder = new TextEncoder();
  const localParts: Uint8Array[] = [];
  const centralParts: Uint8Array[] = [];
  let offset = 0;
  for (const [name, content] of Object.entries(files)) {
    const nameBytes = encoder.encode(name);
    const data = typeof content === "string" ? encoder.encode(content) : content;
    const crc = crc32(data);
    const local = new Uint8Array(30 + nameBytes.length + data.length);
    const view = new DataView(local.buffer);
    view.setUint32(0, 0x04034b50, true); view.setUint16(4, 20, true); view.setUint16(6, 0, true); view.setUint16(8, 0, true);
    view.setUint32(14, crc, true); view.setUint32(18, data.length, true); view.setUint32(22, data.length, true); view.setUint16(26, nameBytes.length, true);
    local.set(nameBytes, 30); local.set(data, 30 + nameBytes.length);
    localParts.push(local);
    const central = new Uint8Array(46 + nameBytes.length);
    const cv = new DataView(central.buffer);
    cv.setUint32(0, 0x02014b50, true); cv.setUint16(4, 20, true); cv.setUint16(6, 20, true); cv.setUint32(16, crc, true);
    cv.setUint32(20, data.length, true); cv.setUint32(24, data.length, true); cv.setUint16(28, nameBytes.length, true); cv.setUint32(42, offset, true);
    central.set(nameBytes, 46); centralParts.push(central); offset += local.length;
  }
  const centralLength = centralParts.reduce((sum, part) => sum + part.length, 0);
  const end = new Uint8Array(22);
  const ev = new DataView(end.buffer);
  ev.setUint32(0, 0x06054b50, true); ev.setUint16(8, centralParts.length, true); ev.setUint16(10, centralParts.length, true);
  ev.setUint32(12, centralLength, true); ev.setUint32(16, offset, true);
  const all = [...localParts, ...centralParts, end];
  const total = all.reduce((sum, part) => sum + part.length, 0);
  const output = new Uint8Array(total);
  let cursor = 0;
  all.forEach(part => { output.set(part, cursor); cursor += part.length; });
  return output;
}

function crc32(data: Uint8Array) {
  let crc = 0xffffffff;
  for (const byte of data) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
  }
  return (crc ^ 0xffffffff) >>> 0;
}
function columnName(index: number) {
  let value = index + 1;
  let result = "";
  while (value) { value--; result = String.fromCharCode(65 + (value % 26)) + result; value = Math.floor(value / 26); }
  return result;
}
function byteLength(value: string) { return new TextEncoder().encode(value).length; }
function xml(value: string) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
function pdf(value: string) { return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)").replace(/[^\x20-\x7E]/g, "?"); }
function save(blob: Blob, name: string) {
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = name;
  link.click();
  setTimeout(() => URL.revokeObjectURL(link.href), 1000);
}
