import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, Pencil, Plus, RotateCcw, Trash2, UsersRound } from "lucide-react";
import { DataTable, type DataTableBulkAction, type DataTableColumn } from "@/components/data-table";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/ui/page-header";
import { OrganizationTableCard, formatDateTime } from "@/features/organization/components/organization-ui";
import { useAuthStore } from "@/stores/auth-store";
import * as api from "../api/telemetry-group-api";
import { GroupForm } from "../components/group-form";
import type { TelemetryGroup, TelemetryGroupInput, TelemetryGroupLog } from "../types/telemetry-group";

export function TelemetryGroupPage(){
 const qc=useQueryClient(),user=useAuthStore(s=>s.user),role=(user?.role||"").replace(/[_ -]/g,"").toUpperCase(),viewOnly=role==="TECHUSER",canPermanent=["SUPERADMIN","OWNER"].includes(role);
 const [tab,setTab]=useState<"LIST"|"LOG"|"WASTED">("LIST"),[editing,setEditing]=useState<TelemetryGroup|null|undefined>(),[view,setView]=useState<TelemetryGroup|null>(null),[notice,setNotice]=useState("");
 const groups=useQuery({queryKey:["telemetry-groups"],queryFn:api.getTelemetryGroups}),logs=useQuery({queryKey:["telemetry-group-logs"],queryFn:api.getTelemetryGroupLogs}),wasted=useQuery({queryKey:["telemetry-group-wasted"],queryFn:api.getTelemetryGroupWasted}),devices=useQuery({queryKey:["telemetry-group-devices",editing?.id??null],queryFn:()=>api.getTelemetryGroupDevices(editing?.id)});
 const refresh=()=>qc.invalidateQueries({queryKey:["telemetry"]});
 const mutate=useMutation({mutationFn:async(x:{kind:string;id?:number;input?:TelemetryGroupInput})=>{if(x.kind==="save")return x.id?api.updateTelemetryGroup(x.id,x.input!):api.createTelemetryGroup(x.input!);if(x.kind==="delete")return api.deleteTelemetryGroup(x.id!);if(x.kind==="restore")return api.restoreTelemetryGroup(x.id!);return api.permanentlyDeleteTelemetryGroup(x.id!);},onSuccess:()=>{setEditing(undefined);setNotice("");void qc.invalidateQueries();},onError:e=>setNotice(e instanceof Error?e.message:"Request failed")});
 const columns=useMemo<DataTableColumn<TelemetryGroup>[]>(()=>[{key:"company",label:"Company",value:r=>r.company},{key:"group",label:"Group Name",value:r=>r.groupName},{key:"count",label:"Device Count",value:r=>r.deviceCount},{key:"createdBy",label:"Created By",value:r=>r.createdBy},{key:"createdAt",label:"Created At",value:r=>formatDateTime(r.createdAt)}],[]);
 const wastedColumns=useMemo<DataTableColumn<TelemetryGroup>[]>(()=>[{key:"company",label:"Company",value:r=>r.company},{key:"group",label:"Group",value:r=>r.groupName},{key:"count",label:"Device Count",value:r=>r.deviceCount},{key:"deletedBy",label:"Deleted By",value:r=>r.deletedBy||"-"},{key:"deletedAt",label:"Deleted At",value:r=>formatDateTime(r.deletedAt)},{key:"permanent",label:"Permanent Delete At",value:r=>formatDateTime(r.deletePermanentAt)}],[]);
 const logColumns=useMemo<DataTableColumn<TelemetryGroupLog>[]>(()=>[{key:"time",label:"Time",value:r=>formatDateTime(r.time)},{key:"action",label:"Action",value:r=>r.action},{key:"company",label:"Company",value:r=>r.company},{key:"group",label:"Group",value:r=>r.group},{key:"user",label:"User",value:r=>r.user},{key:"count",label:"Device Count",value:r=>r.deviceCount},{key:"details",label:"Details",value:r=>r.details}],[]);
 const bulk=useMemo<DataTableBulkAction<TelemetryGroup>[]>(()=>viewOnly?[]:[{key:"delete",label:"Delete",icon:<Trash2 className="h-4 w-4"/>,confirmMessage:r=>`Move ${r.length} group(s) to Wasted?`,onClick:r=>r.forEach(x=>mutate.mutate({kind:"delete",id:x.id}))}],[viewOnly]);
 if(editing!==undefined)return <GroupForm group={editing} devices={devices.data||[]} notice={notice} saving={mutate.isPending} onCancel={()=>{setEditing(undefined);setNotice("");}} onSave={input=>mutate.mutate({kind:"save",id:editing?.id,input})}/>;
 if(view)return <section className="space-y-4 text-foreground"><PageHeader icon={<Eye className="h-5 w-5"/>} title="View Telemetry Group"/><OrganizationTableCard><dl className="grid gap-4 md:grid-cols-2"><div><dt className="text-sm text-muted-foreground">Group Name</dt><dd className="font-bold">{view.groupName}</dd></div><div><dt className="text-sm text-muted-foreground">Company</dt><dd>{view.company}</dd></div><div><dt className="text-sm text-muted-foreground">Device Count</dt><dd>{view.deviceCount}</dd></div><div><dt className="text-sm text-muted-foreground">Created By</dt><dd>{view.createdBy}</dd></div><div className="md:col-span-2"><dt className="text-sm text-muted-foreground">Description</dt><dd>{view.description||"-"}</dd></div></dl><div className="mt-5 flex justify-end"><Button variant="outline" onClick={()=>setView(null)}>Close</Button></div></OrganizationTableCard></section>;
 return <section className="space-y-5"><PageHeader icon={<UsersRound className="h-5 w-5"/>} title="Telemetry > Group" actions={!viewOnly?<Button onClick={()=>setEditing(null)}><Plus className="h-4 w-4"/>Created New</Button>:undefined}/><OrganizationTableCard>{notice?<div className="mb-3 rounded-lg border border-border bg-muted p-3 text-sm text-foreground">{notice}</div>:null}<div className="mb-4 flex gap-2">{(["LIST","LOG","WASTED"] as const).map(x=><Button key={x} variant={tab===x?"default":"outline"} onClick={()=>setTab(x)}>{x[0]+x.slice(1).toLowerCase()}</Button>)}</div>{tab==="LIST"?<DataTable data={groups.data||[]} columns={columns} rowKey={r=>r.id} bulkActions={bulk} actions={r=><div className="flex flex-wrap gap-1"><Button size="icon" variant="outline" onClick={()=>setView(r)} title="View"><Eye className="h-4 w-4"/></Button>{!viewOnly?<><Button size="icon" variant="outline" onClick={()=>setEditing(r)} title="Edit / Add Device / Move Device"><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="destructive" onClick={()=>confirm("Move group to Wasted?")&&mutate.mutate({kind:"delete",id:r.id})}><Trash2 className="h-4 w-4"/></Button></>:null}</div>}/>:tab==="LOG"?<DataTable data={logs.data||[]} columns={logColumns} rowKey={(r)=>`${r.time}-${r.action}-${r.group}`}/>:<DataTable data={wasted.data||[]} columns={wastedColumns} rowKey={r=>r.id} actions={r=><div className="flex gap-1"><Button size="sm" variant="outline" onClick={()=>mutate.mutate({kind:"restore",id:r.id})}><RotateCcw className="h-4 w-4"/>Restore</Button>{canPermanent?<Button size="sm" variant="destructive" onClick={()=>confirm("Permanently delete group membership?")&&mutate.mutate({kind:"permanent",id:r.id})}>Permanent Delete</Button>:null}</div>}/>}</OrganizationTableCard></section>;
}
