package com.alels.backend.telemetry.device.deviceworkspace.tab.logsmessage.controller;
import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*;
import com.alels.backend.serverops.shared.security.JwtUserContext; import com.alels.backend.telemetry.device.deviceworkspace.tab.logsmessage.dto.DeviceWorkspaceLogsMessageDtos.*; import com.alels.backend.telemetry.device.deviceworkspace.tab.logsmessage.service.DeviceWorkspaceLogsMessageService;
@RestController @RequestMapping("/api/telemetry/devices/{deviceId}/workspace/logs-message")
public class DeviceWorkspaceLogsMessageController {private final DeviceWorkspaceLogsMessageService service; public DeviceWorkspaceLogsMessageController(DeviceWorkspaceLogsMessageService service){this.service=service;}
 @GetMapping("/traffic") public Page<TrafficRow> traffic(Authentication a,@PathVariable long deviceId,@RequestParam String from,@RequestParam String to,@RequestParam(defaultValue="") String search,@RequestParam(defaultValue="") String eventType,@RequestParam(defaultValue="") String transport,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="15") int size){return service.traffic(user(a),deviceId,from,to,search,eventType,transport,page,size);}
 @GetMapping("/packets") public Page<PacketRow> packets(Authentication a,@PathVariable long deviceId,@RequestParam String from,@RequestParam String to,@RequestParam(defaultValue="") String direction,@RequestParam(defaultValue="0") int page,@RequestParam(defaultValue="15") int size){return service.packets(user(a),deviceId,from,to,direction,page,size);}
 @GetMapping("/packets/summary") public PacketSummary summary(Authentication a,@PathVariable long deviceId,@RequestParam String from,@RequestParam String to){return service.summary(user(a),deviceId,from,to);}
 @GetMapping("/packets/{packetId}") public PacketDetail detail(Authentication a,@PathVariable long deviceId,@PathVariable long packetId){return service.detail(user(a),deviceId,packetId);} private JwtUserContext user(Authentication a){return (JwtUserContext)a.getPrincipal();}}
